/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package crmpsico;

import java.util.Scanner;

/**
 *
 * @author luanv
 */
public class Crmpsico {
    
    
    public static String scanner(){
        Scanner scan = new Scanner(System.in);
        String digite = scan.next();
        
        return digite;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        System.out.println("Bem vindo ao CRM");
        System.out.println("Digite seu nome: ");
        System.out.println(scanner());
         
    }
    
}
